# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: emailpb.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'emailpb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import corepb_pb2 as corepb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\remailpb.proto\x12\x0egamepb.emailpb\x1a\x0c\x63orepb.proto\"\'\n\x13GetEmailListRequest\x12\x10\n\x08\x62ox_type\x18\x01 \x01(\x05\"p\n\tEmailItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tmail_type\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63laimed\x18\x04 \x01(\x08\x12\x12\n\nhas_reward\x18\x05 \x01(\x08\x12\x10\n\x08subtitle\x18\x07 \x01(\t\">\n\x11GetEmailListReply\x12)\n\x06\x65mails\x18\x01 \x03(\x0b\x32\x19.gamepb.emailpb.EmailItem\"6\n\x10ReadEmailRequest\x12\x10\n\x08\x62ox_type\x18\x01 \x01(\x05\x12\x10\n\x08\x65mail_id\x18\x02 \x01(\t\"\x10\n\x0eReadEmailReply\"7\n\x11\x43laimEmailRequest\x12\x10\n\x08\x62ox_type\x18\x01 \x01(\x05\x12\x10\n\x08\x65mail_id\x18\x02 \x01(\t\".\n\x0f\x43laimEmailReply\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.corepb.Item\"<\n\x16\x42\x61tchClaimEmailRequest\x12\x10\n\x08\x62ox_type\x18\x01 \x01(\x05\x12\x10\n\x08\x65mail_id\x18\x02 \x01(\t\"3\n\x14\x42\x61tchClaimEmailReply\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.corepb.Itemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emailpb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETEMAILLISTREQUEST']._serialized_start=47
  _globals['_GETEMAILLISTREQUEST']._serialized_end=86
  _globals['_EMAILITEM']._serialized_start=88
  _globals['_EMAILITEM']._serialized_end=200
  _globals['_GETEMAILLISTREPLY']._serialized_start=202
  _globals['_GETEMAILLISTREPLY']._serialized_end=264
  _globals['_READEMAILREQUEST']._serialized_start=266
  _globals['_READEMAILREQUEST']._serialized_end=320
  _globals['_READEMAILREPLY']._serialized_start=322
  _globals['_READEMAILREPLY']._serialized_end=338
  _globals['_CLAIMEMAILREQUEST']._serialized_start=340
  _globals['_CLAIMEMAILREQUEST']._serialized_end=395
  _globals['_CLAIMEMAILREPLY']._serialized_start=397
  _globals['_CLAIMEMAILREPLY']._serialized_end=443
  _globals['_BATCHCLAIMEMAILREQUEST']._serialized_start=445
  _globals['_BATCHCLAIMEMAILREQUEST']._serialized_end=505
  _globals['_BATCHCLAIMEMAILREPLY']._serialized_start=507
  _globals['_BATCHCLAIMEMAILREPLY']._serialized_end=558
# @@protoc_insertion_point(module_scope)
