# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: illustratedpb.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'illustratedpb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import corepb_pb2 as corepb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13illustratedpb.proto\x12\x14gamepb.illustratedpb\x1a\x0c\x63orepb.proto\"<\n\x1bGetIllustratedListV2Request\x12\x0f\n\x07refresh\x18\x01 \x01(\x08\x12\x0c\n\x04\x66ull\x18\x02 \x01(\x08\"\xae\x01\n\x0fIllustratedItem\x12\x0f\n\x07seed_id\x18\x01 \x01(\x03\x12\x10\n\x08unlocked\x18\x02 \x01(\x08\x12\x0f\n\x07planted\x18\x03 \x01(\x08\x12\x15\n\rplanted_count\x18\x04 \x01(\x05\x12\x15\n\rharvest_count\x18\x05 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\x05\x12\x13\n\x0breward_info\x18\x07 \x01(\x0c\x12\x12\n\nhas_reward\x18\x08 \x01(\x08\"Q\n\x19GetIllustratedListV2Reply\x12\x34\n\x05items\x18\x01 \x03(\x0b\x32%.gamepb.illustratedpb.IllustratedItem\"2\n\x18\x43laimAllRewardsV2Request\x12\x16\n\x0eonly_claimable\x18\x01 \x01(\x08\"X\n\x16\x43laimAllRewardsV2Reply\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.corepb.Item\x12!\n\x0b\x62onus_items\x18\x04 \x03(\x0b\x32\x0c.corepb.Item\"!\n\x1fIllustratedRewardRedDotNotifyV2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'illustratedpb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETILLUSTRATEDLISTV2REQUEST']._serialized_start=59
  _globals['_GETILLUSTRATEDLISTV2REQUEST']._serialized_end=119
  _globals['_ILLUSTRATEDITEM']._serialized_start=122
  _globals['_ILLUSTRATEDITEM']._serialized_end=296
  _globals['_GETILLUSTRATEDLISTV2REPLY']._serialized_start=298
  _globals['_GETILLUSTRATEDLISTV2REPLY']._serialized_end=379
  _globals['_CLAIMALLREWARDSV2REQUEST']._serialized_start=381
  _globals['_CLAIMALLREWARDSV2REQUEST']._serialized_end=431
  _globals['_CLAIMALLREWARDSV2REPLY']._serialized_start=433
  _globals['_CLAIMALLREWARDSV2REPLY']._serialized_end=521
  _globals['_ILLUSTRATEDREWARDREDDOTNOTIFYV2']._serialized_start=523
  _globals['_ILLUSTRATEDREWARDREDDOTNOTIFYV2']._serialized_end=556
# @@protoc_insertion_point(module_scope)
