# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mallpb.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mallpb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import corepb_pb2 as corepb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmallpb.proto\x12\rgamepb.mallpb\x1a\x0c\x63orepb.proto\"1\n\x1cGetMallListBySlotTypeRequest\x12\x11\n\tslot_type\x18\x01 \x01(\x05\"F\n\x1dGetMallListBySlotTypeResponse\x12\x12\n\ngoods_list\x18\x01 \x03(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"\xa0\x01\n\tMallGoods\x12\x10\n\x08goods_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x10\n\x08item_ids\x18\x04 \x01(\x0c\x12\r\n\x05price\x18\x05 \x01(\x0c\x12\x0f\n\x07is_free\x18\x06 \x01(\x08\x12\r\n\x05limit\x18\x07 \x01(\x0c\x12\x12\n\nis_limited\x18\x08 \x01(\x08\x12\x10\n\x08\x64iscount\x18\n \x01(\t\"2\n\x0fPurchaseRequest\x12\x10\n\x08goods_id\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"X\n\x10PurchaseResponse\x12\x10\n\x08goods_id\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x13\n\x0breward_info\x18\x03 \x01(\x0c\x12\x0e\n\x06result\x18\x05 \x01(\x0c\"\x1a\n\x18GetMonthCardInfosRequest\"R\n\rMonthCardInfo\x12\x10\n\x08goods_id\x18\x01 \x01(\x05\x12\x1c\n\x06reward\x18\x02 \x01(\x0b\x32\x0c.corepb.Item\x12\x11\n\tcan_claim\x18\x03 \x01(\x08\"E\n\x16GetMonthCardInfosReply\x12+\n\x05infos\x18\x01 \x03(\x0b\x32\x1c.gamepb.mallpb.MonthCardInfo\"/\n\x1b\x43laimMonthCardRewardRequest\x12\x10\n\x08goods_id\x18\x01 \x01(\x05\"8\n\x19\x43laimMonthCardRewardReply\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.corepb.Item2\xa1\x03\n\x0bMallService\x12r\n\x15GetMallListBySlotType\x12+.gamepb.mallpb.GetMallListBySlotTypeRequest\x1a,.gamepb.mallpb.GetMallListBySlotTypeResponse\x12K\n\x08Purchase\x12\x1e.gamepb.mallpb.PurchaseRequest\x1a\x1f.gamepb.mallpb.PurchaseResponse\x12\x63\n\x11GetMonthCardInfos\x12\'.gamepb.mallpb.GetMonthCardInfosRequest\x1a%.gamepb.mallpb.GetMonthCardInfosReply\x12l\n\x14\x43laimMonthCardReward\x12*.gamepb.mallpb.ClaimMonthCardRewardRequest\x1a(.gamepb.mallpb.ClaimMonthCardRewardReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mallpb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMALLLISTBYSLOTTYPEREQUEST']._serialized_start=45
  _globals['_GETMALLLISTBYSLOTTYPEREQUEST']._serialized_end=94
  _globals['_GETMALLLISTBYSLOTTYPERESPONSE']._serialized_start=96
  _globals['_GETMALLLISTBYSLOTTYPERESPONSE']._serialized_end=166
  _globals['_MALLGOODS']._serialized_start=169
  _globals['_MALLGOODS']._serialized_end=329
  _globals['_PURCHASEREQUEST']._serialized_start=331
  _globals['_PURCHASEREQUEST']._serialized_end=381
  _globals['_PURCHASERESPONSE']._serialized_start=383
  _globals['_PURCHASERESPONSE']._serialized_end=471
  _globals['_GETMONTHCARDINFOSREQUEST']._serialized_start=473
  _globals['_GETMONTHCARDINFOSREQUEST']._serialized_end=499
  _globals['_MONTHCARDINFO']._serialized_start=501
  _globals['_MONTHCARDINFO']._serialized_end=583
  _globals['_GETMONTHCARDINFOSREPLY']._serialized_start=585
  _globals['_GETMONTHCARDINFOSREPLY']._serialized_end=654
  _globals['_CLAIMMONTHCARDREWARDREQUEST']._serialized_start=656
  _globals['_CLAIMMONTHCARDREWARDREQUEST']._serialized_end=703
  _globals['_CLAIMMONTHCARDREWARDREPLY']._serialized_start=705
  _globals['_CLAIMMONTHCARDREWARDREPLY']._serialized_end=761
  _globals['_MALLSERVICE']._serialized_start=764
  _globals['_MALLSERVICE']._serialized_end=1181
# @@protoc_insertion_point(module_scope)
