# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qqvippb.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'qqvippb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import corepb_pb2 as corepb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rqqvippb.proto\x12\x0egamepb.qqvippb\x1a\x0c\x63orepb.proto\"\x1b\n\x19GetDailyGiftStatusRequest\">\n\x17GetDailyGiftStatusReply\x12\x11\n\tcan_claim\x18\x01 \x01(\x08\x12\x10\n\x08has_gift\x18\x02 \x01(\x08\"\x17\n\x15\x43laimDailyGiftRequest\"2\n\x13\x43laimDailyGiftReply\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.corepb.Itemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qqvippb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDAILYGIFTSTATUSREQUEST']._serialized_start=47
  _globals['_GETDAILYGIFTSTATUSREQUEST']._serialized_end=74
  _globals['_GETDAILYGIFTSTATUSREPLY']._serialized_start=76
  _globals['_GETDAILYGIFTSTATUSREPLY']._serialized_end=138
  _globals['_CLAIMDAILYGIFTREQUEST']._serialized_start=140
  _globals['_CLAIMDAILYGIFTREQUEST']._serialized_end=163
  _globals['_CLAIMDAILYGIFTREPLY']._serialized_start=165
  _globals['_CLAIMDAILYGIFTREPLY']._serialized_end=215
# @@protoc_insertion_point(module_scope)
