# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sharepb.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sharepb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import corepb_pb2 as corepb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsharepb.proto\x12\x0egamepb.sharepb\x1a\x0c\x63orepb.proto\"\x16\n\x14\x43heckCanShareRequest\"\'\n\x12\x43heckCanShareReply\x12\x11\n\tcan_share\x18\x01 \x01(\x08\"$\n\x12ReportShareRequest\x12\x0e\n\x06shared\x18\x01 \x01(\x08\"#\n\x10ReportShareReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"*\n\x17\x43laimShareRewardRequest\x12\x0f\n\x07\x63laimed\x18\x01 \x01(\x08\"Y\n\x15\x43laimShareRewardReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nhas_reward\x18\x02 \x01(\x08\x12\x1b\n\x05items\x18\x03 \x03(\x0b\x32\x0c.corepb.Itemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sharepb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKCANSHAREREQUEST']._serialized_start=47
  _globals['_CHECKCANSHAREREQUEST']._serialized_end=69
  _globals['_CHECKCANSHAREREPLY']._serialized_start=71
  _globals['_CHECKCANSHAREREPLY']._serialized_end=110
  _globals['_REPORTSHAREREQUEST']._serialized_start=112
  _globals['_REPORTSHAREREQUEST']._serialized_end=148
  _globals['_REPORTSHAREREPLY']._serialized_start=150
  _globals['_REPORTSHAREREPLY']._serialized_end=185
  _globals['_CLAIMSHAREREWARDREQUEST']._serialized_start=187
  _globals['_CLAIMSHAREREWARDREQUEST']._serialized_end=229
  _globals['_CLAIMSHAREREWARDREPLY']._serialized_start=231
  _globals['_CLAIMSHAREREWARDREPLY']._serialized_end=320
# @@protoc_insertion_point(module_scope)
